title: Home
author: Ilia Kaziamov
description:
lang : en

remote_theme: b2a3e8/jekyll-theme-console
style: hacker
listen_for_clients_preferred_style : true

disqus:
  shortname: kaziamov-github-com


header_pages:
- index.md
- about.md
- course-free/index.md
- solo-journey/index.md

collections:
  solo-journey:
    output: true
    permalink: /solo-journey/:name

plugins:
  - disqus-for-jekyll